#ifndef __BOARD_CONF_H__
#define __BOARD_CONF_H__

#define CONFIG_USING_GPIO_LED       1
#define CONFIG_USING_GPIO_BEEP      1
#define CONFIG_USING_GPIO_KEY       1
#define CONFIG_USING_GPIO_STEPPER   0
#define CONFIG_USING_GPIO_DCMOTOR   0

#define CONFIG_USING_XINTF_LCD1602  0
#define CONFIG_USING_XINTF_LCD12864 0

#define CONFIG_USING_TIM0_DEMO_IRQ  1
#define CONFIG_USING_TIM1_DEMO_IRQ  1
#define CONFIG_USING_TIM2_DEMO_IRQ  1

// SCIx_Printf ( 若输出乱码, 可尝试增大缓冲长度 )
//#define CONFIG_SPRINTF_BUFFER_SIZE 64
#define CONFIG_SPRINTF_BUFFER_SIZE  128

#if CONFIG_USING_GPIO_KEY

  #define CONFIG_USING_EXIT_DEMO_IRQ 1
  // 0:Disable, 1: XINT1.4 (XINT1,EXTI1_IRQn), 2: XINT1.5 (XINT2,EXTI2_IRQn)
  #define CONFIG_USING_EXIT_KEY3     1
  // 0:Disable, 1: XINT12.1 (XINT3,EXTI3_IRQn)
  #define CONFIG_USING_EXIT_KEY4     1
  // 0:Disable, 1: XINT12.1 (XINT4,EXTI4_IRQn)
  #define CONFIG_USING_EXIT_KEY5     1

#endif

#define CONFIG_USING_SCIB_RS232 1

#if CONFIG_USING_SCIB_RS232

  #define CONFIG_SCIB_FRAME_FORMAT (SCI_CFG_DATABITS_8 | SCI_CFG_PARITY_NONE | SCI_CFG_STOPBITS_ONE)
  #define CONFIG_SCIB_BAUDRATE     115200
    // #define CONFIG_SCIB_BAUDRATE   1171875

  #define CONFIG_USING_SCIB_PRINTF 0

#endif

#define CONFIG_USING_SCIC_RS232 0

#if CONFIG_USING_SCIC_RS232

  #define CONFIG_SCIC_FRAME_FORMAT (SCI_CFG_DATABITS_8 | SCI_CFG_PARITY_NONE | SCI_CFG_STOPBITS_ONE)

  #define CONFIG_SCIC_BAUDRATE     115200
    // #define CONFIG_SCIC_BAUDRATE     921600
    // #define CONFIG_SCIC_BAUDRATE     1171875

  #define CONFIG_USING_SCIC_PRINTF 1

#endif

#endif  // __BOARD_CONF_H__
